### PR TITLE
[POZ-17] Billboard Creator Web App: Front-end configuration. Used Vue 2.

### PR DESCRIPTION
**Pull request by Jess-Nguy**
## Link Jira ticket:
https://jess-nguy.atlassian.net/browse/POZ-17
## Author Notes:
Reinstalled vue with vue 2 and added bootstrap, vuetify, and router.
This comes with eslint and babel as well.
Combined Readmes so that it's easier to read.
Added axios with a test call for home page for now which uses the billboard server endpoint.

## Impacts and Notes:
instructions on how to run whole program is now in 1 doc.

## Testing Guidance:
Read readme to see how to run it and the changes
Should see this:
image

## Author Checklist:

- [x] Tested locally.
- [x] Change Jira ticket status to into Review.
- [x] Updated the documentation.

### CODE REVIEW

**Comment by Jess-Nguy** [comment]
I don't see an axios install for front end endpoints jira ticket. I'll be adding that to this ticket since this ticket is about setting up configs. Please hold on review till I've finished.

**Comment by Jess-Nguy** [comment]
Added a test call for home for now which uses the billboard server endpoint.

**Comment by salihelfatih** [comment]
let's gooo! 👌

**Review by salihelfatih — COMMENTED** [review]
very nice!

**Comment by richardfigueroa** [comment]
Sorry for the delay I know this is already merged I fixed my computer issues and was able to build this locally and confirmed it work.

**Pull request merged**
